version: 2.1

executors:
  svelte-starter:
    docker:
      - image: circleci/node:12

jobs:
  test:
    executor: svelte-starter
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Combat preparation
          command: docker-compose up -d
      - run:
          name: Test the application
          command: |
            docker-compose exec app yarn unit
            docker-compose exec app yarn _codecov -t $CODECOV_TOKEN
